'use client';

import { useState, useEffect, useMemo, useRef } from 'react';
import { Article, ArticleStatus } from '@/types';
import Button from '@/components/ui/Button';

interface ArticleEditorProps {
  article: Article;
  onChange: (updated: Article) => void;
}

interface Config {
  categories: string[];
  tags: string[];
}

const statusOptions: { label: string; value: ArticleStatus }[] = [
  { label: '草稿', value: ArticleStatus.DRAFT },
  { label: '已发布', value: ArticleStatus.PUBLISHED },
  { label: '已归档', value: ArticleStatus.ARCHIVED },
];

function cleanHtmlTags(content: string): string {
  return content
    .replace(/<font[^>]*>/gi, '')
    .replace(/<\/font>/gi, '');
}

function generateSlugPreview(title: string): string {
  if (!title.trim()) return '';
  return title
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w\u4e00-\u9fff-]/g, '')
    .slice(0, 60);
}

export default function ArticleEditor({ article, onChange }: ArticleEditorProps) {
  const [config, setConfig] = useState<Config>({ categories: [], tags: [] });
  const [newCategoryInput, setNewCategoryInput] = useState('');
  const [newTagInput, setNewTagInput] = useState('');
  const [showAddCategory, setShowAddCategory] = useState(false);
  const [showAddTag, setShowAddTag] = useState(false);
  const [categoryOpen, setCategoryOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const categoryRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetch('/api/config')
      .then((res) => res.json())
      .then((data) => {
        if (data.success) setConfig(data.data);
      });
  }, []);

  useEffect(() => {
    if (!categoryOpen) return;
    function handleClick(e: MouseEvent) {
      if (categoryRef.current && !categoryRef.current.contains(e.target as Node)) {
        setCategoryOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [categoryOpen]);

  function updateFrontmatter(field: string, value: unknown) {
    onChange({
      ...article,
      frontmatter: { ...article.frontmatter, [field]: value },
    });
  }

  async function saveConfig(updated: Config) {
    setConfig(updated);
    try {
      await fetch('/api/config', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updated),
      });
    } catch { }
  }

  async function handleAddCategory() {
    const cat = newCategoryInput.trim();
    if (!cat || config.categories.includes(cat)) {
      setNewCategoryInput('');
      setShowAddCategory(false);
      return;
    }
    const updated = { ...config, categories: [...config.categories, cat] };
    await saveConfig(updated);
    updateFrontmatter('category', cat);
    setNewCategoryInput('');
    setShowAddCategory(false);
  }

  function handleToggleTag(tag: string) {
    const current = article.frontmatter.tags;
    if (current.includes(tag)) {
      updateFrontmatter('tags', current.filter((t) => t !== tag));
    } else {
      updateFrontmatter('tags', [...current, tag]);
    }
  }

  async function handleAddCustomTag() {
    const tag = newTagInput.trim();
    if (!tag || config.tags.includes(tag)) {
      setNewTagInput('');
      setShowAddTag(false);
      return;
    }
    const updated = { ...config, tags: [...config.tags, tag] };
    await saveConfig(updated);
    handleToggleTag(tag);
    setNewTagInput('');
    setShowAddTag(false);
  }

  function handleCleanHtml() {
    const cleaned = cleanHtmlTags(article.content);
    if (cleaned === article.content) return;
    onChange({ ...article, content: cleaned });
  }

  const { displaySlug, isAutoGenerated } = useMemo(() => {
    if (article.slug) return { displaySlug: article.slug, isAutoGenerated: false };
    return { displaySlug: generateSlugPreview(article.frontmatter.title), isAutoGenerated: true };
  }, [article.slug, article.frontmatter.title]);

  const contentStats = useMemo(() => {
    const text = article.content || '';
    const chars = text.length;
    const lines = text.split('\n').length;
    const words = text.trim() ? text.trim().split(/\s+/).length : 0;
    return { chars, lines, words };
  }, [article.content]);

  return (
    <div className="flex flex-col flex-1 min-h-0">
      <div className={`flex h-full overflow-hidden ${sidebarCollapsed ? '' : 'gap-5'}`}>
        {sidebarCollapsed ? (
          <div className="shrink-0 w-[36px] flex flex-col items-center pt-4 border-r border-border-gray/40 bg-subtle-bg/30">
            <div className="relative group">
              <button
                type="button"
                onClick={() => setSidebarCollapsed(false)}
                className="w-7 h-7 flex items-center justify-center rounded-md text-muted-text hover:text-secondary-text hover:bg-subtle-bg transition-colors cursor-pointer"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 16 16" stroke="currentColor" strokeWidth={1.5}>
                  <rect x="2.5" y="1.5" width="11" height="13" rx="2" strokeLinecap="round" strokeLinejoin="round" />
                  <path d="M6 1.5v13" strokeLinecap="round" />
                </svg>
              </button>
              <span className="absolute left-full ml-2 top-1/2 -translate-y-1/2 px-2 py-1 text-[0.75rem] text-white bg-gray-800 rounded-md whitespace-nowrap opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-150 pointer-events-none z-50 shadow-lg">
                展开设置
              </span>
            </div>
          </div>
        ) : (
          <div className="w-[300px] shrink-0 overflow-y-auto px-4 pt-4 transition-all duration-200 ease-out">
            <div className="flex items-center justify-between mb-3">
              <span className="text-[0.8rem] font-medium text-muted-text uppercase tracking-wider">文章设置</span>
              <button
                type="button"
                onClick={() => setSidebarCollapsed(true)}
                className="w-6 h-6 flex items-center justify-center rounded text-muted-text hover:text-secondary-text hover:bg-subtle-bg transition-colors cursor-pointer"
                title="收起侧边栏"
              >
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 16 16" stroke="currentColor" strokeWidth={1.5}>
                  <rect x="2.5" y="1.5" width="11" height="13" rx="2" strokeLinecap="round" strokeLinejoin="round" />
                  <path d="M6 1.5v13" strokeLinecap="round" />
                </svg>
              </button>
            </div>
            <div className="py-4 space-y-6">
              <div>
                <h3 className="text-[0.75rem] font-semibold text-muted-text uppercase tracking-wider mb-3">基础信息</h3>

                <div className="space-y-3">
                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">标题</label>
                    <input
                      type="text"
                      value={article.frontmatter.title}
                      onChange={(e) => updateFrontmatter('title', e.target.value)}
                      placeholder="文章标题"
                      className="w-full px-0 py-2.5 text-[1rem] bg-transparent border-b border-border-gray/60 outline-none focus:border-primary transition-colors placeholder:text-muted-text/50 rounded-none"
                    />
                  </div>

                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">
                      Slug
                      {isAutoGenerated && (
                        <span className="ml-1.5 font-normal text-muted-text/50">(自动生成)</span>
                      )}
                    </label>
                    <div className="px-0 py-2.5 border-b border-border-gray/60 text-[1rem] text-secondary-text font-mono truncate">
                      {displaySlug || '-'}
                    </div>
                  </div>

                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">日期</label>
                    <input
                      type="date"
                      value={article.frontmatter.date ? article.frontmatter.date.split('T')[0] : ''}
                      onChange={(e) => updateFrontmatter('date', e.target.value ? new Date(e.target.value).toISOString() : '')}
                      className="w-full px-0 py-2.5 text-[1rem] bg-transparent border-b border-border-gray/60 outline-none focus:border-primary transition-colors rounded-none"
                    />
                  </div>
                </div>
              </div>

              <div className="pt-2">
                <h3 className="text-[0.75rem] font-semibold text-muted-text uppercase tracking-wider mb-3">分类与标签</h3>

                <div className="space-y-3">
                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">分类</label>
                    <div ref={categoryRef} className="relative">
                      <button
                        type="button"
                        onClick={() => setCategoryOpen(!categoryOpen)}
                        className="w-full px-3 py-2.5 pr-8 text-left text-[0.88rem] bg-subtle-bg/50 border border-border-gray/40 rounded-lg outline-none focus:border-primary cursor-pointer transition-colors"
                      >
                        <span className={article.frontmatter.category ? 'text-primary-text' : 'text-muted-text'}>
                          {article.frontmatter.category || '选择分类'}
                        </span>
                      </button>
                      <svg className={`absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-text pointer-events-none transition-transform duration-200 ${categoryOpen ? 'rotate-180' : ''}`} viewBox="0 0 16 16" fill="none">
                        <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                      {categoryOpen && (
                        <div className="absolute z-20 w-full mt-1.5 bg-white border border-border-gray/50 rounded-xl shadow-lg overflow-hidden origin-top animate-in fade-in slide-in-from-top-1 duration-150 ease-out">
                          {config.categories.map((cat, i) => (
                            <button
                              key={cat}
                              type="button"
                              onClick={() => {
                                updateFrontmatter('category', cat);
                                setCategoryOpen(false);
                              }}
                              className={`w-full px-3.5 py-2 text-left text-[0.88rem] transition-colors hover:bg-primary/5 ${article.frontmatter.category === cat ? 'bg-primary/8 text-primary font-medium' : 'text-secondary-text'
                                }`}
                              style={{ animationDelay: `${i * 40}ms` }}
                            >
                              {cat}
                            </button>
                          ))}
                          {config.categories.length === 0 && (
                            <div className="px-3.5 py-2.5 text-[0.81rem] text-muted-text">暂无分类</div>
                          )}
                        </div>
                      )}
                    </div>
                    {!showAddCategory ? (
                      <button
                        onClick={() => setShowAddCategory(true)}
                        className="mt-1.5 text-[0.75rem] text-primary hover:text-primary/80 transition-colors cursor-pointer"
                      >
                        ＋ 新增分类
                      </button>
                    ) : (
                      <div className="flex items-center gap-2 mt-1.5">
                        <div className="relative flex-1">
                          <input
                            type="text"
                            value={newCategoryInput}
                            onChange={(e) => setNewCategoryInput(e.target.value)}
                            onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleAddCategory(); } }}
                            placeholder="输入新分类名"
                            className="w-full px-3 py-2 pr-8 text-[0.88rem] bg-subtle-bg/50 border border-border-gray/40 rounded-lg outline-none focus:border-primary transition-colors placeholder:text-muted-text/50"
                            autoFocus
                          />
                          <button
                            type="button"
                            onClick={() => { setShowAddCategory(false); setNewCategoryInput(''); }}
                            className="absolute right-2 top-1/2 -translate-y-1/2 w-5 h-5 flex items-center justify-center text-muted-text hover:text-secondary-text hover:bg-subtle-bg rounded-md transition-colors cursor-pointer"
                          >
                            ×
                          </button>
                        </div>
                        <button onClick={handleAddCategory} className="px-4 py-2 text-[0.81rem] bg-primary text-white rounded-lg hover:bg-primary/90 cursor-pointer transition-colors shrink-0">确定</button>
                      </div>
                    )}
                  </div>

                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">标签</label>
                    <div className="flex flex-wrap gap-1.5 mb-2">
                      {config.tags.map((tag) => (
                        <button
                          key={tag}
                          onClick={() => handleToggleTag(tag)}
                          className={`px-2.5 py-1 text-[0.75rem] rounded-full border transition-all duration-150 cursor-pointer ${article.frontmatter.tags.includes(tag)
                            ? 'bg-primary/8 text-primary border-primary'
                            : 'border-border-gray/50 text-secondary-text hover:bg-subtle-bg hover:border-border-light'
                            }`}
                        >
                          {tag}
                        </button>
                      ))}
                    </div>
                    {article.frontmatter.tags.filter((t) => !config.tags.includes(t)).map((tag) => (
                      <span key={tag} className="inline-flex items-center gap-1 px-2.5 py-1 text-[0.75rem] bg-subtle-bg/60 text-secondary-text rounded-full border border-border-gray/40 mr-1.5 mb-1.5">
                        {tag}
                        <button
                          onClick={() => updateFrontmatter('tags', article.frontmatter.tags.filter((t) => t !== tag))}
                          className="text-muted-text hover:text-primary cursor-pointer transition-colors ml-0.5"
                        >
                          ×
                        </button>
                      </span>
                    ))}
                    {!showAddTag ? (
                      <button
                        onClick={() => setShowAddTag(true)}
                        className="text-[0.75rem] text-primary hover:text-primary/80 transition-colors cursor-pointer"
                      >
                        ＋ 新增标签
                      </button>
                    ) : (
                      <div className="flex items-center gap-2 mt-1.5">
                        <div className="relative flex-1">
                          <input
                            type="text"
                            value={newTagInput}
                            onChange={(e) => setNewTagInput(e.target.value)}
                            onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleAddCustomTag(); } }}
                            placeholder="输入新标签名"
                            className="w-full px-3 py-2 pr-8 text-[0.88rem] bg-subtle-bg/50 border border-border-gray/40 rounded-lg outline-none focus:border-primary transition-colors placeholder:text-muted-text/50"
                            autoFocus
                          />
                          <button
                            type="button"
                            onClick={() => { setShowAddTag(false); setNewTagInput(''); }}
                            className="absolute right-2 top-1/2 -translate-y-1/2 w-5 h-5 flex items-center justify-center text-muted-text hover:text-secondary-text hover:bg-subtle-bg rounded-md transition-colors cursor-pointer"
                          >
                            ×
                          </button>
                        </div>
                        <button onClick={handleAddCustomTag} className="px-4 py-2 text-[0.81rem] bg-primary text-white rounded-lg hover:bg-primary/90 cursor-pointer transition-colors shrink-0">确定</button>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              <div className="pt-2">
                <h3 className="text-[0.75rem] font-semibold text-muted-text uppercase tracking-wider mb-3">发布设置</h3>

                <div className="space-y-4">
                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">摘要</label>
                    <textarea
                      value={article.frontmatter.summary}
                      onChange={(e) => updateFrontmatter('summary', e.target.value)}
                      placeholder="请输入文章摘要（80~100字）..."
                      rows={6}
                      className="w-full px-3 py-2.5 text-[0.88rem] bg-subtle-bg/50 border border-border-gray/40 rounded-md outline-none resize-y focus:border-primary transition-colors placeholder:text-muted-text/50 leading-relaxed min-h-[160px]"
                    />
                    <p className="text-[0.69rem] text-muted-text mt-1.5">{(article.frontmatter.summary || '').length}/100 字</p>
                  </div>

                  <div>
                    <label className="block text-[0.75rem] font-medium text-secondary-text mb-1.5">状态</label>
                    <div className="flex items-center gap-1.5">
                      {statusOptions.map((opt) => (
                        <button
                          key={opt.value}
                          onClick={() => updateFrontmatter('status', opt.value)}
                          className={`px-3 py-1.5 text-[0.81rem] rounded-full border transition-all duration-150 cursor-pointer ${article.frontmatter.status === opt.value
                            ? 'bg-primary text-white border-primary shadow-sm'
                            : 'border-border-gray/60 text-secondary-text hover:bg-subtle-bg hover:border-border-light'
                            }`}
                        >
                          {opt.label}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-1">
                    <label className="text-[0.81rem] text-secondary-text">置顶文章</label>
                    <button
                      onClick={() => updateFrontmatter('featured', !article.frontmatter.featured)}
                      className={`w-9 h-[22px] rounded-full transition-colors relative cursor-pointer ${article.frontmatter.featured ? 'bg-primary' : 'bg-border-gray'
                        }`}
                    >
                      <span
                        className={`absolute top-[2px] w-[18px] h-[18px] bg-white rounded-full shadow-sm transition-transform ${article.frontmatter.featured ? 'left-[18px]' : 'left-[2px]'
                          }`}
                      />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        <div className={`flex-1 min-w-0 flex flex-col ${sidebarCollapsed ? '' : 'border-l border-border-gray pl-5'}`}>
          <div className="flex items-center justify-between pb-3 border-b border-border-gray">
            <label className="text-[0.81rem] font-medium text-secondary-text">内容 (Markdown)</label>
            <div className="flex items-center gap-2 pt-2 pr-2">
              <Button variant="ghost" size="sm" onClick={handleCleanHtml}>
                清除 HTML 标签
              </Button>
            </div>
          </div>

          <textarea
            value={article.content}
            onChange={(e) => onChange({ ...article, content: e.target.value })}
            placeholder="在此编写 Markdown 格式的文章内容..."
            className="flex-1 w-full px-4 py-3 text-[0.88rem] text-primary-text bg-transparent outline-none resize-none placeholder:text-muted-text leading-relaxed font-mono min-h-[500px]"
          />

          <div className="flex items-center justify-between px-4 py-2 border-t border-border-gray text-[0.75rem] text-muted-text bg-subtle-bg/30">
            <div className="flex items-center gap-4">
              <span>{contentStats.chars} 字符</span>
              <span>{contentStats.words} 词</span>
              <span>{contentStats.lines} 行</span>
            </div>
            <span>Markdown</span>
          </div>
        </div>
      </div>
    </div>
  );
}
